In [200]:
import glob

In [201]:
import librosa
import soundfile
import os, glob, pickle
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [202]:
#Extract features (mfcc, chroma, mel) from a sound file
def extract_feature(file_name, mfcc, chroma, mel):
    with soundfile.SoundFile(file_name) as sound_file:
        X = sound_file.read(dtype="float32")
        sample_rate=sound_file.samplerate
        if chroma:
            stft=np.abs(librosa.stft(X))
        result=np.array([])
        if mfcc:
            mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T, axis=0)
            result=np.hstack((result, mfccs))
        if chroma:
            chroma=np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
            result=np.hstack((result, chroma))
        if mel:
            mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
            result=np.hstack((result, mel))
    return result

In [203]:
#Emotions in the RAVDESS dataset
emotions={
  '01':'neutral',
  '02':'calm',
  '03':'happy',
  '04':'sad',
  '05':'angry',
  '06':'fearful',
  '07':'disgust',
  '08':'surprised'
}

#Emotions to observe
observed_emotions=['calm', 'happy', 'surprised', 'sad', 'angry']

In [204]:
#Load the data and extract features for each sound file
def load_data(test_size=0.2):
    x,y=[],[]
    for file in glob.glob(r"C:\Users\AFSHAN KHAN\OneDrive\Desktop\itt\speech-emotion-recognition-ravdess-data\\Actor_*\\*.wav"):
        file_name=os.path.basename(file)
        emotion=emotions[file_name.split("-")[2]]
        if emotion not in observed_emotions:
            continue
        feature=extract_feature(file, mfcc=True, chroma=True, mel=True)
        x.append(feature)
        y.append([emotion,file_name])
    return train_test_split(np.array(x), y, test_size=test_size, random_state=35)

In [205]:
#Split the dataset
x_train,x_test,y_train,y_test=load_data(test_size=0.2)
print(np.shape(x_train),np.shape(x_test),np.shape(y_train),np.shape(y_test))
y_test_map=np.array(y_test).T
y_test=y_test_map[0]
test_filename=y_test_map[1]
y_train_map=np.array(y_train).T
y_train=y_train_map[0]
train_filename=y_train_map[1]
print(np.shape(y_train),np.shape(y_test))
print(*test_filename,sep="\n")


C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0. 0. 0. ... 0. 0. 0.] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.0000000e+00 3.0517578e-05 3.0517578e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00  0.0000000e+00 -3.0517578e-05 ... -3.0517578e-05
 -3.0517578e-05 -3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 5.1879883e-04 -6.1035156e-05 -4.2724609e-04 ...  0.0000000e+00
 -9.1552734e-05 -6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 1.2207031e-04  1.5258789e-04 -3.0517578e-05 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error


C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.0000000e+00 0.0000000e+00 0.0000000e+00 ... 6.1035156e-05 0.0000000e+00
 0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[3.0517578e-05 0.0000000e+00 0.0000000e+00 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-1.2207031e-04 -9.1552734e-05 -9.1552734e-05 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[3.0517578e-05 0.0000000e+00 3.0517578e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.         0.         0.         ... 0.00012207 0.00012207 0.00012207] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-3.0517578e-05 -3.0517578e-05 -6.1035156e-05 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.fea

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-6.1035156e-05  0.0000000e+00  3.0517578e-05 ...  2.7465820e-04
  2.4414062e-04  2.7465820e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00 -3.0517578e-05 -3.0517578e-05 ...  6.1035156e-05
  9.1552734e-05  9.1552734e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 2.1362305e-04  7.9345703e-04 -1.2207031e-04 ...  6.1035156e-05
  6.1035156e-05  0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an 

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[3.0517578e-05 6.1035156e-05 3.0517578e-05 ... 0.0000000e+00 0.0000000e+00
 0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-9.1552734e-05 -6.1035156e-05 -6.1035156e-05 ...  6.1035156e-05
  3.0517578e-05 -6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 9.1552734e-05  9.1552734e-05  9.1552734e-05 ... -3.6621094e-04
 -3.6621094e-04 -3.6621094e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error


C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.         0.         0.         ... 0.00033569 0.00036621 0.00036621] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.          0.          0.         ... -0.00100708 -0.00100708
 -0.00100708] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00 -3.0517578e-05 -3.0517578e-05 ... -3.0517578e-04
 -2.4414062e-04 -2.4414062e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspec

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 3.0517578e-05  0.0000000e+00  3.0517578e-05 ...  0.0000000e+00
 -9.1552734e-05  3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00  0.0000000e+00  3.0517578e-05 ...  3.9672852e-04
  4.5776367e-04 -2.7465820e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-2.7465820e-04  1.8310547e-04 -6.1035156e-05 ...  9.1552734e-05
  1.2207031e-04  9.1552734e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an 

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00 -3.0517578e-05  0.0000000e+00 ...  0.0000000e+00
  0.0000000e+00  0.0000000e+00] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[6.1035156e-05 9.1552734e-05 6.1035156e-05 ... 3.0517578e-05 6.1035156e-05
 6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-1.2207031e-04 -6.1035156e-05 -9.1552734e-05 ... -3.0517578e-05
 -6.1035156e-05 -6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error


C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-6.1035156e-05 -6.1035156e-05 -3.0517578e-05 ... -6.1035156e-05
 -9.1552734e-05 -3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00 -3.0517578e-05  0.0000000e+00 ...  3.0517578e-05
  3.0517578e-05  3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.          0.          0.         ... -0.00021362 -0.00024414
 -0.00018311] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mea

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[3.0517578e-05 0.0000000e+00 3.0517578e-05 ... 0.0000000e+00 3.0517578e-05
 3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-9.1552734e-05 -6.1035156e-05  0.0000000e+00 ... -1.8310547e-04
 -1.8310547e-04 -2.1362305e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[6.1035156e-05 6.1035156e-05 3.0517578e-05 ... 1.8310547e-04 1.8310547e-04
 1.8310547e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.          0.          0.         ... -0.00012207 -0.00012207
 -0.00012207] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-6.1035156e-05 -6.1035156e-05 -6.1035156e-05 ...  1.2207031e-04
  1.5258789e-04  9.1552734e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-6.1035156e-05 -6.1035156e-05 -3.0517578e-05 ... -3.0517578e-05
 -3.0517578e-05 -3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mea

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-3.0517578e-05 -3.0517578e-05 -3.0517578e-05 ... -6.1035156e-05
 -6.1035156e-05 -9.1552734e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-3.0517578e-04 -3.3569336e-04 -5.7983398e-04 ...  6.1035156e-05
  9.1552734e-05  6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-9.1552734e-05 -6.1035156e-05 -6.1035156e-05 ... -1.5258789e-04
 -1.5258789e-04 -1.5258789e-04] as keyword args. From version 0.10 passing these as positional arguments will result in an 

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 1.2207031e-04  1.2207031e-04  1.2207031e-04 ... -3.0517578e-05
  0.0000000e+00 -3.0517578e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.          0.          0.         ... -0.00125122 -0.00125122
 -0.00125122] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[-0.0022583  -0.00228882 -0.00234985 ...  0.          0.
  0.        ] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspect

(768, 180) (192, 180) (768, 2) (192, 2)
(768,) (192,)
03-01-05-01-02-01-22.wav
03-01-02-01-01-02-07.wav
03-01-05-01-01-01-15.wav
03-01-08-02-02-02-12.wav
03-01-08-01-02-01-15.wav
03-01-04-01-02-01-04.wav
03-01-08-02-02-01-05.wav
03-01-03-02-02-01-19.wav
03-01-04-01-01-01-11.wav
03-01-08-01-01-01-06.wav
03-01-04-02-02-02-22.wav
03-01-05-01-02-02-20.wav
03-01-02-02-01-02-16.wav
03-01-03-01-02-01-04.wav
03-01-08-01-02-01-10.wav
03-01-03-02-01-01-10.wav
03-01-03-01-02-01-16.wav
03-01-03-01-01-02-13.wav
03-01-02-01-01-02-08.wav
03-01-05-01-02-01-03.wav
03-01-08-02-01-02-02.wav
03-01-04-01-02-01-06.wav
03-01-03-02-02-02-06.wav
03-01-04-01-02-01-11.wav
03-01-08-01-01-02-08.wav
03-01-02-01-01-02-05.wav
03-01-03-02-01-01-19.wav
03-01-05-02-02-01-12.wav
03-01-05-01-02-02-13.wav
03-01-03-01-02-02-16.wav
03-01-04-02-01-02-15.wav
03-01-08-02-02-02-16.wav
03-01-08-01-01-01-19.wav
03-01-04-01-01-02-16.wav
03-01-05-02-02-02-19.wav
03-01-08-02-01-01-17.wav
03-01-04-02-01-01-17.wav
03-01-03-01-01-02-12.

C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[ 0.0000000e+00  0.0000000e+00  0.0000000e+00 ... -3.0517578e-05
 -3.0517578e-05 -6.1035156e-05] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
C:\Users\Abhinaya\AppData\Local\Temp/ipykernel_17716/852816848.py:16: FutureWarning: Pass y=[0.         0.         0.         ... 0.00015259 0.00012207 0.00012207] as keyword args. From version 0.10 passing these as positional arguments will result in an error
  mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)


In [206]:
#Get the shape of the training and testing datasets
print((x_train.shape[0], x_test.shape[0]))

(768, 192)


In [207]:
#Get the number of features extracted
print(f'Features extracted: {x_train.shape[1]}')

Features extracted: 180


In [208]:
#Initialize the Multi Layer Perceptron Classifier
model=MLPClassifier(alpha=0.01, batch_size=256, epsilon=1e-08, hidden_layer_sizes=(300,), learning_rate='adaptive', max_iter=500)

In [209]:
#Train the model
model.fit(x_train,y_train)

MLPClassifier(alpha=0.01, batch_size=256, hidden_layer_sizes=(300,),
              learning_rate='adaptive', max_iter=500)

In [210]:
#Predict for the test set
import pandas as pd
import numpy as np

y_pred=model.predict(x_test)
y_pred1=pd.DataFrame(y_pred,columns=['predictions'])
y_pred1['file_names']=test_filename
print(y_pred1)
y_pred1.to_csv('predictionFinal.csv')

    predictions                file_names
0         happy  03-01-05-01-02-01-22.wav
1          calm  03-01-02-01-01-02-07.wav
2     surprised  03-01-05-01-01-01-15.wav
3     surprised  03-01-08-02-02-02-12.wav
4           sad  03-01-08-01-02-01-15.wav
..          ...                       ...
187        calm  03-01-02-01-02-02-02.wav
188        calm  03-01-02-01-02-01-06.wav
189       angry  03-01-03-02-01-02-16.wav
190        calm  03-01-02-02-01-02-06.wav
191   surprised  03-01-08-01-02-01-22.wav

[192 rows x 2 columns]


In [211]:
#Calculate the accuracy of our model
accuracy=accuracy_score(y_true=y_test, y_pred=y_pred)

#Print the accuracy
print("Accuracy: {:.2f}%".format(accuracy*100))

Accuracy: 69.27%


In [212]:
#classification report
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

       angry       0.67      0.83      0.74        35
        calm       0.73      0.94      0.82        34
       happy       0.71      0.47      0.57        36
         sad       0.57      0.47      0.52        36
   surprised       0.75      0.75      0.75        51

    accuracy                           0.69       192
   macro avg       0.68      0.69      0.68       192
weighted avg       0.69      0.69      0.68       192



In [213]:
#confusion matrix
from sklearn.metrics import confusion_matrix
matrix = confusion_matrix(y_test,y_pred)
print (matrix)


[[29  0  2  0  4]
 [ 0 32  0  2  0]
 [ 9  1 17  5  4]
 [ 1 10  3 17  5]
 [ 4  1  2  6 38]]
